apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-uploader
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-uploader
  template:
    metadata:
      labels:
        app: s3-uploader
    spec:
      serviceAccountName: app
      containers:
      - name: s3-uploader
        image: asixl/pod-to-s3:latest
